"""
Report Generator

Automated marketing performance reports.
"""

import asyncio
from dataclasses import dataclass
from typing import Dict, List, Optional
from datetime import datetime, timedelta
from pathlib import Path

from ..foundation.llm_router import generate_parallel, TaskType


@dataclass
class ReportConfig:
    """Configuration for a report."""
    name: str
    date_range: str  # today, 7d, 30d, 90d, custom
    start_date: str = ""
    end_date: str = ""
    channels: List[str] = None
    sections: List[str] = None  # executive, channel, creative, trends, recommendations
    format: str = "markdown"  # markdown, html, pdf


class ReportGenerator:
    """
    Generates automated marketing performance reports.
    
    Usage:
        generator = ReportGenerator()
        report = await generator.generate_weekly_report(
            date_range="7d",
            sections=["executive", "channel", "recommendations"]
        )
    """
    
    def __init__(self):
        self.output_dir = Path("reports")
        self.output_dir.mkdir(exist_ok=True)
    
    async def generate_weekly_report(
        self,
        date_range: str = "7d",
        channels: List[str] = None,
        sections: List[str] = None,
    ) -> str:
        """Generate a weekly performance report."""
        
        if sections is None:
            sections = ["executive", "channel", "trends", "recommendations"]
        
        if channels is None:
            channels = ["google", "meta", "linkedin", "email"]
        
        report_sections = []
        
        for section in sections:
            if section == "executive":
                content = await self._generate_executive_summary(date_range, channels)
                report_sections.append(f"## Executive Summary\n\n{content}")
            
            elif section == "channel":
                content = await self._generate_channel_analysis(date_range, channels)
                report_sections.append(f"## Channel Performance\n\n{content}")
            
            elif section == "trends":
                content = await self._generate_trends_section(date_range)
                report_sections.append(f"## Performance Trends\n\n{content}")
            
            elif section == "recommendations":
                content = await self._generate_recommendations(date_range, channels)
                report_sections.append(f"## Recommendations\n\n{content}")
        
        report = f"""# Marketing Performance Report
**Date Range:** Last {date_range.replace('d', ' days')}
**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}

---

{"".join(report_sections)}

---

*Report generated by Marketic - Marketing Intelligence OS*
"""
        
        return report
    
    async def _generate_executive_summary(self, date_range: str, channels: List[str]) -> str:
        """Generate executive summary section using AI."""
        
        prompt = f"""Write a concise executive summary for a marketing performance report.

Context:
- Report period: Last {date_range}
- Channels: {', '.join(channels)}
- Focus on: Key wins, overall performance vs targets, ROI highlights

Keep it to 3-4 paragraphs max. Include specific numbers where relevant."""

        responses = await generate_parallel(
            prompt=prompt,
            task_type=TaskType.ANALYTICS,
            temperature=0.5,
            max_tokens=1024,
        )
        
        return responses[0].content if responses else "Executive summary generation failed."
    
    async def _generate_channel_analysis(self, date_range: str, channels: List[str]) -> str:
        """Generate channel performance analysis."""
        
        prompt = f"""Write a channel performance analysis section for a marketing report.

Channels to analyze: {', '.join(channels)}
Period: Last {date_range}

Include:
1. Top performing channel and why
2. Underperforming channels and causes
3. Budget allocation effectiveness
4. Channel synergies

Format as markdown with headers."""

        responses = await generate_parallel(
            prompt=prompt,
            task_type=TaskType.ANALYTICS,
            temperature=0.5,
            max_tokens=1536,
        )
        
        return responses[0].content if responses else "Channel analysis generation failed."
    
    async def _generate_trends_section(self, date_range: str) -> str:
        """Generate performance trends section."""
        
        prompt = f"""Write a trends section analyzing marketing performance trends.

Period: Last {date_range}

Cover:
1. Week-over-week changes
2. Notable spikes or drops
3. Seasonal patterns
4. Audience behavior shifts

Keep it data-informed but concise."""

        responses = await generate_parallel(
            prompt=prompt,
            task_type=TaskType.ANALYTICS,
            temperature=0.5,
            max_tokens=1024,
        )
        
        return responses[0].content if responses else "Trends generation failed."
    
    async def _generate_recommendations(self, date_range: str, channels: List[str]) -> str:
        """Generate actionable recommendations section."""
        
        prompt = f"""Generate 5 specific, actionable recommendations for improving marketing performance.

Channels: {', '.join(channels)}
Period: Last {date_range}

For each recommendation include:
1. What to do (specific action)
2. Why it will help (reasoning)
3. Expected impact (quantified if possible)

Format as numbered list with bold action items."""

        responses = await generate_parallel(
            prompt=prompt,
            task_type=TaskType.OPTIMIZATION,
            temperature=0.6,
            max_tokens=1536,
        )
        
        return responses[0].content if responses else "Recommendations generation failed."
    
    async def generate_campaign_report(
        self,
        campaign_id: str,
        campaign_data: Dict,
    ) -> str:
        """Generate a specific campaign performance report."""
        
        campaign_name = campaign_data.get("name", campaign_id)
        spend = campaign_data.get("spend", 0)
        revenue = campaign_data.get("revenue", 0)
        roas = campaign_data.get("roas", 0)
        conversions = campaign_data.get("conversions", 0)
        cpa = campaign_data.get("cpa", 0)
        
        prompt = f"""Write a campaign performance narrative for:

Campaign: {campaign_name}
Total Spend: ${spend:,.0f}
Revenue: ${revenue:,.0f}
ROAS: {roas:.2f}x
Conversions: {conversions}
CPA: ${cpa:.2f}

Include:
1. Campaign overview and objectives
2. Performance against KPIs
3. Key learnings
4. Best performing elements
5. Next steps

Format as professional marketing report narrative."""

        responses = await generate_parallel(
            prompt=prompt,
            task_type=TaskType.ANALYTICS,
            temperature=0.6,
            max_tokens=2048,
        )
        
        report = f"""# Campaign Performance Report
**Campaign:** {campaign_name}
**Campaign ID:** {campaign_id}
**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}

---

{responses[0].content if responses else "Report generation failed."}

---

### Performance Summary

| Metric | Value |
|--------|-------|
| Total Spend | ${spend:,.0f} |
| Revenue | ${revenue:,.0f} |
| ROAS | {roas:.2f}x |
| Conversions | {conversions:,} |
| CPA | ${cpa:.2f} |

---
*Generated by Marketic*
"""
        
        return report
    
    def save_report(self, report: str, filename: str) -> str:
        """Save report to file."""
        filepath = self.output_dir / f"{filename}.md"
        filepath.write_text(report)
        return str(filepath)


async def demo():
    """Demo report generation."""
    print("=" * 60)
    print("MARKETIC REPORT GENERATOR DEMO")
    print("=" * 60)
    
    generator = ReportGenerator()
    
    print("\n📄 Generating Weekly Report...")
    report = await generator.generate_weekly_report(
        date_range="7d",
        channels=["google_search", "meta_feed", "linkedin"],
        sections=["executive", "channel", "recommendations"],
    )
    
    print("\nReport Preview:")
    print("-" * 40)
    lines = report.split("\n")
    for line in lines[10:30]:
        print(line)
    print("...")
    
    # Save report
    filepath = generator.save_report(report, "weekly_report_demo")
    print(f"\n✅ Report saved to: {filepath}")
    
    return report


if __name__ == "__main__":
    asyncio.run(demo())
